INSERT INTO PERSON (PERSON_ID, FIRST_NAME, LAST_NAME, SSN, MAIL, PASSWORD)
VALUES (1, 'Maria', 'Ravander', '123456789012', 'maria@kth.se', 'bkjbjb');

INSERT INTO ROLE(ID,NAME)
VALUES (1,'APPLICANT');