DROP TABLE IF EXISTS `CONVERSION2`;

--
-- Create for table `CONVERSION`
--
CREATE TABLE `CONVERSION2`
( `CON_FROMTO3` varchar(50) NOT NULL,
  `CON_RATE3`   double(50) NOT NULL,
  `CON_COUNT3` int (10) NOT NULL,
  PRIMARY KEY(`CON_FROMTO`));

